lesson_8/geekshop/adminapp/urls.py
from django.urls import path
from adminapp import views as admin_views

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', admin_views.user_create, name='user_create'),
    path('users/', admin_views.UsersListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.user_update, name='user_update'),
    path('users/delete/<int:pk>/', admin_views.user_delete, name='user_delete'),

    path('categories/create/', admin_views.category_create, name='category_create'),
    path('categories/', admin_views.categories, name='category_list'),
    path('categories/update/<int:pk>/', admin_views.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', admin_views.category_delete, name='category_delete'),

    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', admin_views.ProductsViewList.as_view(), name='product_list'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/detail/<int:pk>/', admin_views.ProductDetailView.as_view(), name='product_detail'),
]

lesson_8/geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

lesson_8/geekshop/basketapp/urls.py
from django.urls import path
from basketapp import views as basket


app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name="basket"),
    path('add/<int:pk>/', basket.add, name="add"),
    path('remove/<int:pk>/', basket.remove, name="remove"),
    path('edit/<int:pk>/<int:quantity>/', basket.edit, name="edit")
]

lesson_8/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.index, name="index"),
    path('contact/', mainapp.contact, name="contact"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),

    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('adminSet/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson_8/geekshop/mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name="products"),
    path('category/<int:pk>/', mainapp.products, name="category"),
    path('category/<int:pk>/<page>/', mainapp.products, name="category_page"),
    path('product/<int:pk>/', mainapp.product, name="product")
]

lesson_8/geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    description = models.TextField(blank=True, verbose_name='описание')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='категория'
        verbose_name_plural='категории'
        # ordering=('-id',)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, blank=True, verbose_name='краткое описание')
    description = models.TextField(blank=True, verbose_name='описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name='цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество на складе')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    def delete(self):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()

lesson_8/geekshop/mainapp/views.py
import random
from django.shortcuts import render

from mainapp.models import Product, ProductCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from basketapp.models import Basket
from django.shortcuts import get_object_or_404


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return []

def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)[0]

def get_some_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)
    return same_products

def product(request, pk):
    links_menu = ProductCategory.objects.all()
    context = {
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
        'links_menu': links_menu
    }
    return render(request, 'mainapp/product.html', context)



def index(request):
    context = {
        'title': 'Главная',
        'products': Product.objects.all()[:4],
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    context = {
        'title': 'Контакты',
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/contact.html', context)


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {
                'name': 'все',
                'pk': 0
            }
        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)

        # page = request.GET.get('p', 1) => аналог "page = 1"
        paginator = Paginator(products_list, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'links_menu': links_menu,
            'title': 'продукты',
            'category': category_item,
            'products': products_paginator,
            'basket': get_basket(request.user)
        }
        return render(request, 'mainapp/products_list.html', context=context)

    hot_product = get_hot_product()
    same_products = get_some_products(hot_product)
    context = {
        'links_menu': links_menu,
        'title': 'продукты',
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/products.html', context=context)

lesson_8/geekshop/mainapp/templates/mainapp/includs/inc_categories_menu.html
<ul class="links-menu">
    <li><a href="{% url 'products:category' 0 %}"
            {% if request.resolver_match.url_name == 'products' %}class="active"{% endif %}>
        Все</a></li>
    {% for link_item in links_menu %}
        <li><a
                href="{% url 'products:category' link_item.pk %}"
                {% if request.resolver_match.kwargs.pk == link_item.pk %}class="active"{% endif %}
        >{{ link_item.name }}</a></li>
    {% endfor %}
</ul>

lesson_8/geekshop/mainapp/templates/mainapp/includs/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <!--Главная-->
    <li><a href="{% url 'index' %}"
                {% if request.resolver_match.url_name == 'index' %}class='active'{% endif %}
        >домой</a></li>

    <!--Продукты-->
    <li><a href="{% url 'products:products' %}"
                {% if request.resolver_match.namespace == 'products' %}class='active'{% endif %}
        >продукты</a></li>

    <!--Контакты-->
    <li><a href="{% url 'contact' %}"
                {% if request.resolver_match.url_name == 'contact' %}class='active'{% endif %}
        >контакты</a></li>

    <!--Вход, Выход, Регистрация, Пользователь-->
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:edit' %}">{{ user.first_name|default:'пользователь' }}</a>
                {% if user.is_superuser %}
                    <li><a href="{% url 'adminapp:user_list' %}">админка</a></li>
                {% endif %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:register' %}">регистрация</a>
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
</ul>
<!--Поиск-->
<a href="#" class="search"></a>

<!--Корзина-->
<a href="{% url 'basket:basket' %}" class="basket">
    <span style="color:red;">
        {% if user.is_authenticated %}
            {% if basket %}
                {{ basket.0.total_cost|floatformat:1 }} руб. <br>
                {{ basket.0.total_quantity }} шт.
            {% endif %}
        {% endif %}
    </span>
</a>